name: hackatum
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - bokeh
    - numpy
    - nodejs
    - pandas
    - pip
    - pip:
        - azure
        - python-dotenv
        - docker
    
